#!/usr/bin/env python3
"""Regenerate beatmaps/manifest.json from the files in this folder.

Pairs every audio file with a beatmap JSON of the same name (stem). Existing
manifest entries are kept so curated names/charts survive; new files dropped
into this folder are appended. Run it after adding audio files or beatmap JSONs:

    python3 beatmaps/scan.py
"""
import json
import os

folder = os.path.dirname(os.path.abspath(__file__))
path = lambda f: os.path.join(folder, f)
AUDIO_EXT = ('.mp3', '.ogg', '.wav', '.m4a', '.flac')

audio = sorted(f for f in os.listdir(folder) if f.lower().endswith(AUDIO_EXT))
charts = sorted(f for f in os.listdir(folder)
                if f.lower().endswith('.json') and f != 'manifest.json')
stem = lambda f: os.path.splitext(f)[0]
norm = lambda s: ''.join(c for c in s.lower() if c.isalnum())
chart_for = {stem(f): f for f in charts}


def match_chart(audio_file):
    exact = chart_for.get(stem(audio_file))
    if exact:
        return exact
    na = norm(stem(audio_file))
    best, best_len = None, -1
    for c in charts:
        nc = norm(stem(c))
        if (nc in na or na in nc) and len(nc) > best_len:
            best, best_len = c, len(nc)
    return best or ''

old = []
if os.path.exists(path('manifest.json')):
    with open(path('manifest.json'), encoding='utf-8') as fh:
        old = json.load(fh).get('demos', [])
old_by_audio = {d['audio']: d for d in old}
audio_set = set(audio)

demos = []
for d in old:
    if d['audio'] in audio_set:
        chart = d['chart'] if d['chart'] and os.path.exists(path(d['chart'])) else match_chart(d['audio'])
        demos.append({
            'name': d['name'],
            'audio': d['audio'],
            'chart': chart,
        })
for f in audio:
    if f in old_by_audio:
        continue
    demos.append({
        'name': stem(f).replace('_', ' '),
        'audio': f,
        'chart': match_chart(f),
    })

manifest = {
    '_comment': 'Generated by scan.py. Each entry needs a beatmap JSON in this folder to be playable in the menu; empty "chart" means it must be generated (Load MP3 -> Analyze -> Save beatmap to folder).',
    'demos': demos,
}
with open(path('manifest.json'), 'w', encoding='utf-8') as fh:
    json.dump(manifest, fh, indent=2, ensure_ascii=False)
    fh.write('\n')
print('wrote manifest.json with %d demo(s)' % len(demos))
