#!/usr/bin/env node
// Assemble the uploadable game into dist/.
//
//   node build.js        (or: cd tools && npm run build)
//
// dist/ is the game only — no editor, no tools, no unfinished songs. Paths
// inside it match what the dev server serves, so anything that works at
// localhost:8000 works from a static host.
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'src');
const SHARED = path.join(ROOT, 'shared');
const BEATMAPS = path.join(ROOT, 'beatmaps');
const DIST = path.join(ROOT, 'dist');

const AUDIO_EXT = ['.mp3', '.ogg', '.wav', '.m4a', '.flac'];

function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const s = path.join(from, entry.name);
    const d = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

function dirSize(dir) {
  let total = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    total += entry.isDirectory() ? dirSize(p) : fs.statSync(p).size;
  }
  return total;
}

const mb = (bytes) => (bytes / 1024 / 1024).toFixed(2) + ' MB';

function build() {
  fs.rmSync(DIST, { recursive: true, force: true });

  copyDir(SRC, DIST);
  copyDir(SHARED, path.join(DIST, 'shared'));

  // Only ship songs that actually have a chart — a half-finished song can sit
  // in beatmaps/ without turning into a broken menu entry.
  const manifest = JSON.parse(fs.readFileSync(path.join(BEATMAPS, 'manifest.json'), 'utf8'));
  const playable = (manifest.demos || []).filter(
    (d) => d.chart && fs.existsSync(path.join(BEATMAPS, d.chart)) && fs.existsSync(path.join(BEATMAPS, d.audio))
  );
  const skipped = (manifest.demos || []).filter((d) => !playable.includes(d));

  const outBeatmaps = path.join(DIST, 'beatmaps');
  fs.mkdirSync(outBeatmaps, { recursive: true });
  const shipped = new Set();
  for (const d of playable) {
    for (const f of [d.audio, d.chart]) {
      if (shipped.has(f)) continue;
      fs.copyFileSync(path.join(BEATMAPS, f), path.join(outBeatmaps, f));
      shipped.add(f);
    }
  }
  fs.writeFileSync(
    path.join(outBeatmaps, 'manifest.json'),
    JSON.stringify({ _comment: 'Generated by build.js', demos: playable }, null, 2) + '\n'
  );

  console.log('dist/ built\n');
  for (const d of playable) {
    const audio = fs.statSync(path.join(outBeatmaps, d.audio)).size;
    const notes = JSON.parse(fs.readFileSync(path.join(outBeatmaps, d.chart), 'utf8')).notes.length;
    console.log('  ' + d.name.padEnd(28) + mb(audio).padStart(9) + '  ' + notes + ' notes');
  }
  for (const d of skipped) {
    console.log('  ' + d.name.padEnd(28) + '   skipped  (no chart yet)');
  }

  const total = dirSize(DIST);
  const audioTotal = [...shipped]
    .filter((f) => AUDIO_EXT.includes(path.extname(f).toLowerCase()))
    .reduce((a, f) => a + fs.statSync(path.join(outBeatmaps, f)).size, 0);
  const wasm = path.join(DIST, 'vendor', 'essentia', 'essentia-wasm.es.js');
  const wasmSize = fs.existsSync(wasm) ? fs.statSync(wasm).size : 0;

  console.log('\n  audio            ' + mb(audioTotal).padStart(9));
  console.log('  essentia (lazy)  ' + mb(wasmSize).padStart(9) + '   not fetched until Load MP3');
  console.log('  total            ' + mb(total).padStart(9));
  console.log('\nupload dist/ to your host, or push it to a gh-pages branch.');
}

build();
