// Regenerate beatmaps/manifest.json from the folder contents.
// Node port of the former beatmaps/scan.py — same pairing rules: exact stem
// match first, then longest normalized-substring match. Existing entries keep
// their curated name/chart; new audio files are appended.
'use strict';

const fs = require('fs');
const path = require('path');

const AUDIO_EXT = ['.mp3', '.ogg', '.wav', '.m4a', '.flac'];
const COMMENT = 'Generated by tools/manifest.js. Each entry needs a beatmap JSON in this folder to be playable in the menu; empty "chart" means it must be generated (npm run beatmap, or the editor).';

const stem = (f) => f.replace(/\.[^.]+$/, '');
const norm = (s) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

function regenerate(folder) {
  const files = fs.readdirSync(folder);
  const audio = files.filter((f) => AUDIO_EXT.includes(path.extname(f).toLowerCase())).sort();
  const charts = files.filter((f) => f.toLowerCase().endsWith('.json') && f !== 'manifest.json').sort();
  const chartForStem = {};
  for (const c of charts) chartForStem[stem(c)] = c;

  function matchChart(audioFile) {
    const exact = chartForStem[stem(audioFile)];
    if (exact) return exact;
    const na = norm(stem(audioFile));
    let best = null, bestLen = -1;
    for (const c of charts) {
      const nc = norm(stem(c));
      if ((na.includes(nc) || nc.includes(na)) && nc.length > bestLen) {
        best = c;
        bestLen = nc.length;
      }
    }
    return best || '';
  }

  const manifestPath = path.join(folder, 'manifest.json');
  let old = [];
  if (fs.existsSync(manifestPath)) {
    old = JSON.parse(fs.readFileSync(manifestPath, 'utf8')).demos || [];
  }
  const oldAudio = new Set(old.map((d) => d.audio));
  const audioSet = new Set(audio);

  const demos = [];
  for (const d of old) {
    if (!audioSet.has(d.audio)) continue;
    const chart = d.chart && fs.existsSync(path.join(folder, d.chart)) ? d.chart : matchChart(d.audio);
    demos.push({ name: d.name, audio: d.audio, chart });
  }
  for (const f of audio) {
    if (oldAudio.has(f)) continue;
    demos.push({ name: stem(f).replace(/_/g, ' '), audio: f, chart: matchChart(f) });
  }

  const manifest = { _comment: COMMENT, demos };
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
  return demos;
}

module.exports = { regenerate };

if (require.main === module) {
  const folder = process.argv[2] || path.join(__dirname, '..', 'beatmaps');
  const demos = regenerate(folder);
  console.log('wrote manifest.json with ' + demos.length + ' demo(s)');
}
